events/urls.py
from django.urls import path

from . import views

app_name = 'event'


urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("event_detail/<int:event_id>", views.event_detail, name="event_detail"),
    path('event_detail/<int:event_id>/get_tickets/', views.get_tickets, name='get_tickets'),
    path('event_detail/<int:event_id>/save_order/', views.save_order, name='save_order'),
    path('events_page', views.events_page, name="events_page"),
] 

host/urls.py
from django.urls import path

from . import views

app_name = 'host'


urlpatterns = [
    path("", views.index, name="index"),
    path('api/events', views.get_user_events, name='get_user_events'),
    path('manage_event/<int:event_id>/', views.manage_event, name='manage_event'),
    path('manage_event/<int:event_id>/tickets/', views.tickets, name='tickets'),
] 

italawa/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("events.urls")),
    path('host/', include("host.urls")),
    path('accounts/', include('allauth.urls')),
    path('events/', include('events.urls', namespace='event')),
] 

# Serve media files during development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

host/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from django.utils import timezone



User = settings.AUTH_USER_MODEL


class Event(models.Model):
    poster = models.ImageField(upload_to='posters/', blank=True, null=True)
    name = models.CharField(max_length=255)
    category = models.CharField(max_length=100, null=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    description = models.TextField(blank=True)
    undisclosed = models.BooleanField(default=False)
    location = models.CharField(max_length=255, blank=True)
    directions = models.TextField(blank=True)
    socials = models.URLField(blank=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)


class Ticket(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    type = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField()
    description = models.TextField()
    deadline = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    tickets_sold = models.PositiveIntegerField(default=0)
    revenue = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    def update_sales(self, quantity_sold):
        self.tickets_sold += quantity_sold
        self.revenue += quantity_sold * self.price
        self.save()

class Staff(models.Model):
    ROLE_CHOICES = [
        ('admin', 'Admin'),
        ('staff', 'Staff'),
    ]
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    role = models.CharField(max_length=5, choices=ROLE_CHOICES)

host/forms.py
from django import forms
from .models import Event, Ticket


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['poster', 'name', 'category', 'start_time', 'end_time', 'description', 
                'undisclosed', 'location', 'directions', 'socials']
        


class TicketForm(forms.ModelForm):
    class Meta:
        model = Ticket
        fields = ['type', 'price', 'quantity', 'description', 'deadline']

host/views.py
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.core.mail import send_mail
from django.http import JsonResponse, QueryDict, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from datetime import datetime
import json



# Create your views here.
from .forms import EventForm, TicketForm
from .models import Event, Ticket
from events.models import Order

@csrf_exempt
@login_required  
def index(request):
    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.created_by = request.user
            if not event.poster:
                event.poster = 'path/to/default/image.jpg'
            event.save()
            return JsonResponse({
                'success': True,
                'id': event.id,
                'name': event.name,
                'category': event.category,
                'start_time': event.start_time,
                'end_time': event.end_time,
                'description': event.description,
                'location': event.location,
                'undisclosed': event.undisclosed,
                'directions': event.directions,
                'socials': event.socials,
                'poster': event.poster.url if event.poster else None
            })
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = EventForm()
        return render(request, "host/index.html", {'form': form})



def get_user_events(request):
    if request.user.is_authenticated:
        events = Event.objects.filter(created_by=request.user)
        events_data = [{
            'id': event.id,
            'name': event.name,
            'category': event.category,
            'start_time': event.start_time,
            'end_time': event.end_time,
            'description': event.description,
            'location': event.location,
            'undisclosed': event.undisclosed,
            'directions': event.directions,
            'socials': event.socials,
            'poster': event.poster.url if event.poster else None
        } for event in events]
        return JsonResponse(events_data, safe=False)
    else:
        return JsonResponse({'error': 'User not authenticated'}, status=401)


# @csrf_exempt
# @login_required
# def manage_event(request, event_id):
#     print("View reached")  # Debugging line
#     event = get_object_or_404(Event, id=event_id, created_by=request.user)
    
#     if request.method == 'GET' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
#         event_data = {
#             'id': event.id,
#             'name': event.name,
#             'category': event.category,
#             'start_time': event.start_time,
#             'end_time': event.end_time,
#             'description': event.description,
#             'location': event.location,
#             'undisclosed': event.undisclosed,
#             'directions': event.directions,
#             'socials': event.socials,
#             'poster': event.poster.url if event.poster else None
#         }
#         return JsonResponse(event_data)
    
#     if request.method == 'POST' or request.method == 'PUT':
#         print("Handling POST/PUT request")  # Debugging line
#         print("Request POST data:", request.POST)  # Debugging line
#         try:
#             data = request.POST
#             event.name = data.get('name')
#             print(f"Event name: {event.name}")
#             event.category = data.get('category')
#             event.start_time = data.get('start_time')
#             event.end_time = data.get('end_time')
#             event.description = data.get('description')
#             event.location = data.get('location')
#             event.undisclosed = data.get('undisclosed')
#             event.directions = data.get('directions')
#             event.socials = data.get('socials')

#             if 'poster' in request.FILES:
#                 event.poster = request.FILES['poster']
#                 print("Poster file received")  # Debugging line
#             else:
#                 print("No poster file received")
#             event.save()
#             print("Event saved successfully")  # Debugging line
#             return JsonResponse({'success': True, 
#                                 'id': event.id, 
#                                 'name': event.name,
#                                 'category': event.category,
#                                 'start_time': event.start_time,
#                                 'end_time': event.end_time,
#                                 'description': event.description,
#                                 'location': event.location,
#                                 'undisclosed': event.undisclosed,
#                                 'directions': event.directions,
#                                 'socials': event.socials,
#                                 'poster': event.poster.url if event.poster else None
#                             })
#         except json.JSONDecodeError:
#             return JsonResponse({'error': 'Invalid JSON'}, status=400)
    
#     return render(request, 'host/manage_event.html', {'event': event})



@csrf_exempt
@login_required
def manage_event(request, event_id):
    event = get_object_or_404(Event, id=event_id, created_by=request.user)
    
    if request.method == 'GET' and request.headers.get('X-Requested-With') == 'XMLHttpRequest':
        data = {
            'id': event.id,
            'name': event.name,
            'category': event.category,
            'start_time': event.start_time,
            'end_time': event.end_time,
            'description': event.description,
            'location': event.location,
            'undisclosed': event.undisclosed,
            'directions': event.directions,
            'socials': event.socials,
            'poster': event.poster.url if event.poster else None
        }
        return JsonResponse(data)
    
    elif request.method == 'POST':
        # Update event details
        event.name = request.POST.get('name')
        event.category = request.POST.get('category')
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')
        
        if start_time:
            event.start_time = timezone.make_aware(datetime.strptime(start_time, '%Y-%m-%dT%H:%M'))

        if end_time:
            event.end_time = timezone.make_aware(datetime.strptime(end_time, '%Y-%m-%dT%H:%M'))

        event.description = request.POST.get('description')
        event.location = request.POST.get('location')
        event.undisclosed = request.POST.get('undisclosed', False)
        event.directions = request.POST.get('directions')
        event.socials = request.POST.get('socials')
        
        # Handle poster update if a new file is uploaded
        if 'poster' in request.FILES:
            event.poster = request.FILES['poster']
        
        # Save the updated event
        event.save()
        return JsonResponse({'message': 'Event updated successfully',
                            'success': True, 
                            'id': event.id,
                            'name': event.name,
                            'category': event.category,
                            'start_time': event.start_time,
                            'end_time': event.end_time,
                            'description': event.description,
                            'location': event.location,
                            'undisclosed': event.undisclosed,
                            'directions': event.directions,
                            'socials': event.socials,
                            'poster': event.poster.url if event.poster else None
                        }) 
    # Fetch related orders
    orders = Order.objects.filter(ticket__event=event).order_by('-created_at')

    return render(request, 'host/manage_event.html', {'event': event, 'orders': orders})


@csrf_exempt
@login_required
def tickets(request, event_id):
    event = get_object_or_404(Event, id=event_id, created_by=request.user)
    tickets = Ticket.objects.filter(event=event)
    if request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            print("Form is valid")
            ticket = form.save(commit=False)
            ticket.event = event
            ticket.save()
            return JsonResponse({
                'success': True,
                'event_id': event.id,
                'type': ticket.type,
                'price': ticket.price,
                'quantity': ticket.quantity,
                'description': ticket.description,
                'deadline': ticket.deadline
            })
        else:
            print("Form errors:", form.errors)
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = TicketForm()
    return render(request, "host/ticket.html", {'event': event, 'tickets': tickets, 'form': form})

host/templates/host/index.html
{% extends "host/layout.html" %}

{% load static %}



{% block body %}


<div class="container">
    <h2>Welcome, {{ user.creator }}</h2>
    <div class="d-flex justify-content-center align-items-center vh-100">
        <div class="text-center p-4" style="border-radius: 15px; border: 1px solid #ccc; transform: scale(1);">
        <p>"Bring people outside"</p>
        <button class="btn btn-primary" id="openModalButton" onclick="event_details()">+ Create Event</button>
        </div>
    </div>

    <h2>Active Events</h2>
    <div id="events-container" class="row"></div>
</div>



{% endblock %}

{% block script %}
    <script src="{% static 'host/script.js' %}"></script>
{% endblock %}

host/templates/host/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}italawa{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link href="{% static 'host/style.css' %}" rel="stylesheet">
        {% block script %}
        {% endblock %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand ms-2" href="{% url 'host:index' %}">ITALAWA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle me-2" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{ user.creator }}
              </a>
              <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Profile</a></li>
                <li><a class="dropdown-item" href="#">Staff management</a></li>
                <li><a class="dropdown-item" href="{% url 'event:logout' %}">Log out</a></li>

              </ul>
            </li>
          </ul>
        </div>
    </nav>

<!-- Event Modal -->
<div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="eventModalLabel">Create Event</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form id="eventForm" method="POST" enctype="multipart/form-data" data-event-id="{{ event.id }}">
            <div class="mb-3">
                <label for="eventPoster" class="form-label">Event Poster/Flyer</label>
                <input type="file" class="form-control" id="eventPoster" name="poster" accept="image/*" >
            </div>
            <img id="preview" src="#" alt="Image Preview" style="display:none; max-width: 100%; height: auto;">     

            <div class="mb-3">
              <label for="eventName" class="form-label">Event Name</label>
              <input type="text" class="form-control" id="eventName" name="name" required>
            </div>
            <div class="mb-3">
              <label for="eventCategory" class="form-label">Event Category</label>
              <select class="form-select" id="eventCategory" name="category">
                <!-- <option value="{{ event.category }}">{{ event.category }}</option> -->
                <option value="concert">Concert</option>
                <option value="sport">Sport</option>
                <option value="party">Party</option>
                <option value="club">Club</option>
                <option value="tech">Tech</option>
                <option value="others">Others</option>
              </select>
            </div>
            <div class="mb-3">
              <label for="startDateTime" class="form-label">Start Date and Time</label>
              <input type="datetime-local" class="form-control" id="eventStartTime" name="start_time"  required>
            </div>
            <div class="mb-3">
              <label for="endDateTime" class="form-label">End Date and Time</label>
              <input type="datetime-local" class="form-control" id="eventEndTime" name="end_time" required>
            </div>
            <div class="mb-3">
              <label for="eventDescription" class="form-label">Event Description</label>
              <textarea class="form-control" id="eventDescription" name="description" rows="3" ></textarea>
            </div>
            <div class="mb-3">
              <label for="eventLocation" class="form-label">Location/Address</label>
              <input type="text" class="form-control" id="eventLocation" name="location" placeholder="No1, italawa street, lagos" >
            </div>
            <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="undisclosedAddress" name="undisclosed" >
                <label class="form-check-label" for="undisclosedAddress">Mark as Undisclosed</label>
            </div>
            <div class="mb-3">
              <label for="directions" class="form-label">Directions</label>
              <textarea class="form-control" id="directions" name="directions" rows="2"></textarea>
            </div>
            <div class="mb-3">
              <label for="socials" class="form-label">Instagram Link</label>
              <input type="url" class="form-control" id="socials" name="socials" placeholder="https://example.com" value="{{ event.socials }}">
            </div>
            <button type="submit" class="btn btn-primary" id="saveButton" disabled>Save</button>
          </form>
        </div>
      </div>
    </div>
</div>



    {% block body %}
    {% endblock %}
</body>
</html>

host/templates/host/manage_event.html
{% extends "host/layout.html" %}

{% load static %}



{% block body %}
<div>
    {% include "host/sidenav.html" %}
    <div class="main-content">
        <button onclick= "event_details('{{ event.id }}')">Edit Event</button>
        <h2>{{ event.name }}</h2>
        <img src="{{ event.poster.url }}" alt="">
        <h2>Orders</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Full Name</th>
                    <th>Email</th>
                    <th>Ticket Type</th>
                    <th>Ticket Description</th>
                    <th>Quantity</th>
                    <th>Created At</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                <tr>
                    <td>{{ order.full_name }}</td>
                    <td>{{ order.email }}</td>
                    <td>{{ order.ticket.type }}</td>
                    <td>{{ order.ticket.description }}</td>
                    <td>{{ order.quantity }}</td> <!-- Display the purchased quantity -->
                    <td>{{ order.created_at }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="6">No orders found for this event.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>        
    </div>

</div>

    



{% endblock %}

{% block script %}
    <script src="{% static 'host/script.js' %}"></script>
{% endblock %}

host/templates/host/sidenav.html
<div id="sidenav" class="sidenav">
    <a href="{% url 'host:manage_event' event_id=event.id %}" class="nav-item" data-name="Dashboard"><i class="bi bi-graph-up-arrow"></i></a>
    <a href="{% url 'host:tickets' event_id=event.id %}" class="nav-item" data-name="Ticket"><i class="bi bi-ticket-detailed-fill"></i></a>
    <a href="#" class="nav-item" data-name="Revenue"><i class="bi bi-cash-coin"></i></a>
    <a href="#" class="nav-item" data-name="Scan Ticket"><i class="bi bi-qr-code"></i></a>
    <a href="#" class="nav-item" data-name="Staff management"><i class="bi bi-person-fill-gear"></i></a>
</div>

host/templates/host/ticket.html
{% extends "host/layout.html" %}

{% load static %}



{% block body %}
{% include "host/sidenav.html" %}
<div class="main-content">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#ticketModal">
        Create Ticket
    </button>    
    <h2>{{ event.name }}</h2>

    <!-- create ticket modal -->
    <div class="modal fade" id="ticketModal" tabindex="-1" aria-labelledby="ticketModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ticketModalLabel">Create Ticket For {{ event.name }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="ticketForm" method="post" data-event-id="{{ event.id }}">
                        <div class="mb-3">
                        <label for="type" class="form-label">Type</label>
                        <input type="text" class="form-control" id="type" name="type" placeholder="VVIP">
                        </div>
                        <div class="mb-3">
                            <label for="price" class="form-label">Price</label>
                            ₦<input type="number" class="form-control" id="price" name="price">
                            <input type="hidden" id="hiddenPrice" name="price">
                            <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="freeCheckbox">
                                <label class="form-check-label" for="freeCheckbox">
                                    Free
                                </label>
                            </div>
                        </div>
                        <div class="mb-3">
                        <label for="quantity" class="form-label">Quantity</label>
                        <input type="number" class="form-control" id="quantity" name="quantity">
                        </div>
                        <div class="mb-3">
                        <label for="description" class="form-label">Description</label>
                        <textarea class="form-control" id="description" name="description" placeholder="Admits one"></textarea>
                        </div>
                        <div class="mb-3">
                        <label for="deadline" class="form-label">Deadline</label>
                        <input type="date" class="form-control" id="deadline" name="deadline">
                        </div>
                        <button type="submit" class="btn btn-primary" id="createBtn">Create</button>
                    </form>
                    <div id="ticketCard" style="display:none;">
                        <!-- Ticket card content will be displayed here -->
                        <button class="btn btn-secondary" id="addAnotherBtn">Add Another</button>
                        <button class="btn btn-success" id="doneBtn">Done</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <!-- ticket table -->
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Price</th>
                <th>Quantity</th>
                <th>Description</th>
                <th>Deadline</th>
            </tr>
        </thead>
        <tbody>
            {% for ticket in tickets %}
            <tr>
                <td>{{ ticket.type }}</td>
                <td>{% if ticket.price == 0 %}Free{% else %}{{ ticket.price }}{% endif %}</td>
                <td>{{ ticket.quantity }}</td>
                <td>{{ ticket.description }}</td>
                <td>{{ ticket.deadline }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

{% block script %}
    <script src="{% static 'host/script.js' %}"></script>
{% endblock %}